import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx
export default function RootLayout({ children }: { children: React.ReactNode }) {
  const SKIN = process.env.NEXT_PUBLIC_SKIN || 'glass';
  return (
    <html lang="ko">
      <body data-skin={SKIN} className="min-h-dvh antialiased">{children}</body>
    </html>
  );
}

